default:
  image: $CI_REGISTRY/sam.mosleh/docker-with-compose

stages:
  - build
  - deploy

build-stag:
  stage: build
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
    - >
      TAG=stag
      FRONTEND_ENV=staging
      sh ./scripts/build-push.sh
  only:
    - main
  tags:
    - build
    - stag

build-prod:
  stage: build
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
    - >
      TAG=prod
      FRONTEND_ENV=production
      sh ./scripts/build-push.sh
  only:
    - production
  tags:
    - build
    - prod

deploy-stag:
  stage: deploy
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
    - >
      DOMAIN=stag.qpoker.io
      TRAEFIK_TAG=stag.qpoker.io
      STACK_NAME=stag-qpoker-io
      TAG=stag
      PROXY_AUTH=true
      sh ./scripts/deploy.sh
  environment:
    name: staging
    url: https://stag.qpoker.io
  only:
    - main
  tags:
    - swarm
    - stag

deploy-prod:
  stage: deploy
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
    - >
      DOMAIN=qpoker.io
      TRAEFIK_TAG=qpoker.io
      STACK_NAME=qpoker-io
      TAG=prod
      sh ./scripts/deploy.sh
  environment:
    name: production
    url: https://qpoker.io
  only:
    - production
  tags:
    - swarm
    - prod
